#name: rsync

on:
  schedule:
    - cron: 0 6 * * * 
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: rsync
        env:
          TZ: Asia/Shanghai
        run:
          rsync -avrt rsync://op.supes.top/packages /home/runner/work/openwrt-packages/openwrt-packages

      - name: commit
        run: |
          git config --global user.email 1462668901@qq.com
          git config --global user.name hmsjy2017
          git add .
          git commit -m "update" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
